#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:

print(np.__version__)
np.show_config()


1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
print(f"{x.size * x.itemsize} bytes")


80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
x = np.zeros(10)
x[4] = 1
print(x)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
x = np.arange(10,50)
print(x)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
x = x[::-1]
print(x)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
x = np.arange(9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
non_zero = np.nonzero([1,2,0,0,4,0])
print(non_zero)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
x = np.random.rand(3,3,3)
print(x)

[[[0.38786612 0.32262543 0.02452889]
  [0.42488914 0.04410528 0.37430242]
  [0.80347763 0.74333868 0.14350455]]

 [[0.71850291 0.2811561  0.47672797]
  [0.29198753 0.51717354 0.38318964]
  [0.9924253  0.22662499 0.41346469]]

 [[0.8046385  0.23270061 0.64994811]
  [0.99747458 0.62103544 0.17439443]
  [0.6786367  0.97118143 0.34998606]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
x = np.random.rand(3,3,3)
min = x.min()
max = x.max()
print(x)
print()
print(min, max)


[[[0.7766194  0.44470232 0.47419747]
  [0.46300885 0.08076036 0.2487482 ]
  [0.58746225 0.08454782 0.08955581]]

 [[0.07021834 0.30544642 0.98715411]
  [0.39660469 0.72869175 0.47510482]
  [0.48062895 0.5720042  0.00784263]]

 [[0.31390297 0.91905962 0.76727977]
  [0.42935784 0.8557851  0.29651471]
  [0.0314716  0.76963518 0.00110436]]]

0.001104356150747332 0.9871541090736007


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
x = np.random.rand(30)
m = x.mean()
print (x)
print()
print(m)


[0.55287075 0.1901805  0.0262106  0.14625159 0.51285028 0.03622574
 0.19986763 0.31976727 0.43602276 0.2142091  0.47942256 0.42577141
 0.57645015 0.10388639 0.28358314 0.76466181 0.32896571 0.89594708
 0.98940022 0.22546107 0.61535161 0.77879667 0.765038   0.14695241
 0.84984998 0.92408116 0.19865952 0.68763024 0.62972466 0.0716798 ]

0.44585899402161183


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
import numpy as np

rows, cols = map(int, input("Enter the number of rows and cols: ").split())
array = np.zeros((rows, cols), dtype=int)

array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1

print(array)


Enter the number of rows and cols: 5 5
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
borderd = np.pad(array, pad_width=1, mode='constant', constant_values=0)


print("Array with Border of Zeros:")
print(borderd)


Array with Border of Zeros:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan

False

False

nan

True

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
matrix = np.diag([1, 2, 3, 4], k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix = np.zeros((8, 8), dtype=int)

matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 21. Create a checkerboard 8x8 matrix using the tile function (search on it )

In [ ]:
checkerboard_2x2 = np.array([[0, 1], [1, 0]])

checkerboard_8x8 = np.tile(checkerboard_2x2, (4, 4))

print(checkerboard_8x8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix knowing normalization = (x-min/max-min )

> Add blockquote



In [ ]:
matrix = np.random.rand(5, 5)

min = matrix.min()
max = matrix.max()

normalized_matrix = (x-min) / (max-min)

print(normalized_matrix)

[0.55263776 0.1759968  0.00571987 0.13037818 0.51107792 0.01612024
 0.18605654 0.31056806 0.43129526 0.20094965 0.47636441 0.4206496
 0.57712413 0.08638342 0.27299213 0.77257526 0.32012032 0.90891036
 1.00595813 0.21263442 0.61752192 0.78725381 0.77296592 0.13110596
 0.86104016 0.9381266  0.18480196 0.69258071 0.63244782 0.05293803]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matrix_a = np.random.rand(5, 3)
matrix_b = np.random.rand(3, 2)

result = np.dot(matrix_a, matrix_b)

print(result)

[[0.73275123 0.39805983]
 [0.42506084 0.31856589]
 [0.47465285 0.25138372]
 [0.32560931 0.23399815]
 [0.51164795 0.27643803]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array = np.array([1, 2, 4, 5, 6, 7, 8, 9, 10])

array[(array > 3) & (array < 8)] *= -1

print(array)

[ 1  2 -4 -5 -6 -7  8  9 10]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

nan

0   RuntimeWarning: divide by zero encountered in floor_divide

np.array([np.nan])

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
array1 = np.array([1, 2, 3, 4, 5, 6])
array2 = np.array([4, 5, 6, 7, 8, 9])

values = np.intersect1d(array1, array2)

print(values)

[4 5 6]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False

 np.sqrt(-1) will produce a nan, can't handle negative inputs

 np.emath.sqrt(-1) will return 1j , it compute the square root of negative numbers and return a complex result.



#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
from datetime import datetime, timedelta

today = datetime.now().date()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-08-10
Today: 2024-08-11
Tomorrow: 2024-08-12


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
import calendar
from datetime import datetime, timedelta

_, num_days = calendar.monthrange(2016, 7)

dates = [datetime(2016, 7, day) for day in range(1, num_days+1)]

for date in dates:
    print(date.strftime('%Y-%m-%d'))


2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

A += B
result= A* -0.5


print(result)

[-3. -4. -5. -6.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
np.arange(5).reshape(1, 5) + np.arange(5).reshape(5, 1)


array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def integer_generator():
    for i in np.random.randint(50,100,10):
        yield i

generator = integer_generator()
np.array(list(generator))

array([54, 91, 52, 56, 92, 83, 57, 59, 84, 74])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
np.linspace(0, 1, num=12)[1:-1]


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
random_vector = np.random.randint(0,100,10)

np.sort(random_vector)

array([ 0, 10, 16, 21, 37, 45, 46, 84, 98, 98])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
import time

s_time = time.time()

arr = np.array([1, 2, 3, 4, 5])
sum= np.cumsum(arr)[-1]

e_time = time.time()

time = e_time - s_time

print(time)
print(sum)


0.00021576881408691406
15


In [ ]:
import time

s_time = time.time()

arr = np.array([1, 2, 3, 4, 5])
sum= np.sum(arr)

e_time = time.time()

time = e_time - s_time

print(time)
print(sum)

0.00022673606872558594
15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.rand(5)
B = np.random.rand(5)

np.array_equal(A, B)

False

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
vector = np.random.randint(0,100,10)

max_value = np.max(vector)

vector[vector == max_value] = 0

print(vector)

[22 94  0 56 74 42  9 35  9  3]


#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
vector = np.array([1, 5, 10,7, 20, 50])
scalar = 12

differences = np.abs(vector - scalar)

index_of_closest = np.argmin(differences)  #index of minimum diff

closest_value = vector[index_of_closest]

print(closest_value)


10
