### task1
Create a NumPy program to create a 3x3 identity matrix


In [1]:
import numpy as np

identity_mtrx = np.identity(3)
print(identity_mtrx)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### task2
Create a NumPy program to generate 5 random number between 0 and 1



In [6]:
print(np.random.rand(5))

[0.61254137 0.35510113 0.91744472 0.85308809 0.83142218]


### task3
Write a NumPy program to append values to the end of an array.


In [20]:
org_array = np.array([3,5,8])
numbers = list(map(int, input('enter numbers separated by spaces: ').split()))
np.append(org_array,numbers)

enter numbers separated by spaces: 4


array([3, 5, 8, 4])

### task4
Write a NumPy program to create a 3X4 array and iterate over it using nditer.


In [47]:
array = np.array(list(map(int, input('enter 12 numbers to create 3x4 array: ').split())))
array = array.reshape(3, 4)
print (array)

'''for i in range(array.shape[0]):
    for j in range(array.shape[1]):
        print(f'value is {array[i,j]} its postion ({i},{j})')'''

for i in np.nditer(array):
    print(f'value is {i}', end="\n")

enter 12 numbers to create 3x4 array: 1 2 3 4 5 6 7 8 9 10 11 12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
value is 1
value is 2
value is 3
value is 4
value is 5
value is 6
value is 7
value is 8
value is 9
value is 10
value is 11
value is 12


### task5
Write a NumPy program to create a 1-D array then convert it into 2-D array then print value and position for each value using ndenumerate.


In [45]:
while True:
    array = np.array(list(map(int, input('enter numbers separated by spaces: ').split())))
    if len(array) % 2 != 0:
        print('the lenth must be divisible by 2. try again.')
    else:
        reshaped_array = array.reshape(2, len(array) // 2)
        break
print(array)
print(reshaped_array)

'''for i in range(reshaped_array.shape[0]):
    for j in range(reshaped_array.shape[1]):
        print(f'value is {reshaped_array[i,j]} its postion ({i},{j})')'''

for postion , i in np.ndenumerate(array2_d):
    print(f'value is {i}its postion {postion}')

enter numbers separated by spaces: 1 2 3 5 6 7
[1 2 3 5 6 7]
[[1 2 3]
 [5 6 7]]
value is 1 at position (0,0)
value is 2 at position (0,1)
value is 3 at position (0,2)
value is 5 at position (1,0)
value is 6 at position (1,1)
value is 7 at position (1,2)
